apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "express-website.fullname" . }}
  labels:
    {{- include "express-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "express-website.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "express-website.name" . }}
    spec:
      containers:
        - name: express-website
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
{{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
{{- end }}
{{- range $key, $value := .Values.secretEnv }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
