image:
  repository: ghcr.io/krbck/portfolio
  tag: "20260301.3"

replicaCount: 2

service:
  port: 80

virtualService:
  enabled: true
  host: portfolio.krbck.site
  gateway: default/nginx-gateway

probes:
  liveness:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  startup:
    enabled: false  # Enable if your app is slow to start (>30s)
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}