---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: flowfish-backend
    {{- include "flowfish.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: flowfish-frontend
    {{- include "flowfish.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
