---
apiVersion: v1
kind: Service
metadata:
  name: flowfish-backend
  labels:
    app: flowfish-backend
    {{- include "flowfish.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: flowfish-backend
---
apiVersion: v1
kind: Service
metadata:
  name: flowfish-frontend
  labels:
    app: flowfish-frontend
    {{- include "flowfish.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: flowfish-frontend
