replicaCount: 1

image:
  repository: ghcr.io/krbck/express-website
  tag: "20260224.14"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  DB_HOST: postgres.production.svc.cluster.local
  DB_NAME: postgres

secretEnv:
  DB_USER:
    secretName: postgres-secret
    secretKey: POSTGRES_USER
  DB_PASSWORD:
    secretName: postgres-secret
    secretKey: POSTGRES_PASSWORD
  DB_NAME:
    secretName: postgres-secret
    secretKey: POSTGRES_DB

livenessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

virtualService:
  enabled: true
  host: website.krbck.site
  gateway: default/nginx-gateway
  prefix: /api