replicaCount: 1

image:
  repository: ghcr.io/krbck/express-website
  tag: "20260308.17"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  DB_HOST: postgres.production.svc.cluster.local
  DB_NAME: postgres
  REDIS_HOST: redis-0.redis.production.svc.cluster.local

secretEnv:
  DB_USER:
    secretName: postgres-secret
    secretKey: POSTGRES_USER
  DB_PASSWORD:
    secretName: postgres-secret
    secretKey: POSTGRES_PASSWORD
  DB_NAME:
    secretName: postgres-secret
    secretKey: POSTGRES_DB

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

virtualService:
  enabled: true
  host: website.krbck.site
  gateway: default/nginx-gateway
  prefix: /api


probes:
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  startup:
    enabled: true  # Enable if your app is slow to start (>30s)
    httpGet:
      path: /health
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}