image:
  repository: postgres
  tag: "16"
postgres:
  db: appdb
  user: appuser
  password: apppass

service:
  port: 5432

storage:
  size: 2Gi
  storageClassName: "longhorn"   # k3s ise boş bırak

env:
  PGDATA: /var/lib/postgresql/data/pgdata