{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
    - {{ .Values.virtualService.host }}
  gateways:
    - {{ .Values.virtualService.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
