replicaCount: 1

image:
  repository: ghcr.io/krbck/binance-ws-tracker
  tag: "20260425.5"
  pullPolicy: IfNotPresent

datadog:
  enabled: false
  
service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  SYMBOL: "solusdt"
  ALERT_THRESHOLD: "0.5"
  ALERT_COOLDOWN: "60000"
  HEALTH_PORT: "3000"

secretEnv:
  N8N_WEBHOOK_URL:
    secretName: binance-tracker-secret
    secretKey: n8n-webhook-url


livenessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

virtualService:
  enabled: false
  host: api.krbck.site
  gateway: default/nginx-gateway
  prefix: /api

probes:
  liveness:
    enabled: true
    httpGet:
      path: /health
      port: 3000 # Change it to port which app is using
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    httpGet:
      path: /health
      port: 3000 # Change it to port which app is using
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  startup:
    enabled: false  # Enable if your app is slow to start (>30s)
    httpGet:
      path: /
      port: 80 # Change it to port which app is using
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}