replicaCount: 1

image:
  repository: ghcr.io/krbck/mobile-api
  tag: "20260228.2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi


livenessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 5

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

virtualService:
  enabled: true
  host: api.krbck.site
  gateway: default/nginx-gateway
  prefix: /api