apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v1-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/krbck/gitops-config.git
    targetRevision: main
    path: helm-chart
    helm:
      valueFiles:
        - ../applications/v1-website/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
