image:
  repository: ghcr.io/krbck/v1-website
  tag: "20260523.18"

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  enabled: false

autoscaling:
  enabled: false

virtualService:
  enabled: true
  host: website.kuberunner.com
  gateway: default/nginx-gateway

probes:
  liveness:
    enabled: true
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  
  readiness:
    enabled: true
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  
  startup:
    enabled: false  # Enable if your app is slow to start (>30s)
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 30


podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  capabilities:
    drop:
      - ALL
  allowPrivilegeEscalation: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}